"""empty message

Revision ID: 43eb74f183ec
Revises: 
Create Date: 2020-06-24 18:33:49.090793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43eb74f183ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('first_price', sa.Numeric(), nullable=True),
    sa.Column('last_price', sa.Numeric(), nullable=True),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_set')
    # ### end Alembic commands ###
